### ISSUE TITLE
Showing PARSER_FAIL for node, seems issue when showing external table stats

### ISSUE THREAD

**Issue by ankush-bindra** [crst/vrqp#3]
I tried to visualize the below explanation and found many graph nodes with **PARSER_FAIL** caption. Seems, this issue is happening with external tables. Could you please fix this issue?

![image](https://github.com/crst/vrqp/assets/72207611/16520d86-e561-4f8f-8025-ac503762d086)

XN Merge  (cost=35550190915222.17..35550190915222.67 rows=200 width=59)
  Merge Key: a.exp_variant
  ->  XN Network  (cost=35550190915222.17..35550190915222.67 rows=200 width=59)
        Send to leader
        ->  XN Sort  (cost=35550190915222.17..35550190915222.67 rows=200 width=59)
              Sort Key: a.exp_variant
              ->  XN HashAggregate  (cost=34550190915204.03..34550190915214.53 rows=200 width=59)
                    ->  XN Hash Left Join DS_BCAST_INNER  (cost=34448739177986.27..34550190196387.10 rows=22117444 width=59)
                          Hash Cond: ((("outer".ad_id)::text = ("inner".ad_id)::text) AND (("outer".exp_variant)::text = ("inner".exp_variant)::text))
                          ->  XN Subquery Scan a  (cost=22785121666289.92..22785121942757.97 rows=22117444 width=559)
                                ->  XN HashAggregate  (cost=22785121666289.92..22785121721583.53 rows=22117444 width=1148)
                                      ->  XN Subquery Scan volt_dt_1  (cost=22785105631143.67..22785116689865.22 rows=221174431 width=1148)
                                            ->  XN HashAggregate  (cost=22785105631143.67..22785114478120.91 rows=221174431 width=2068)
                                                  ->  XN Hash Join DS_BCAST_INNER  (cost=60527418073.27..17621017560018.00 rows=229515025383363 width=2068)
                                                        Hash Cond: (("outer".session_id)::text = ("inner".session_id)::text)
                                                        ->  XN Hash Join DS_BCAST_INNER  (cost=18652417692.49..577559534399.78 rows=1561751669729 width=2068)
                                                              Hash Cond: (("outer".ad_id)::text = ("inner".ad_id)::text)
                                                              ->  XN Partition Loop  (cost=0.00..200200000010.00 rows=10000000000000 width=1548)
                                                                    ->  XN Seq Scan PartitionInfo of ext_wkda_retail_autohero_ad_view_tracking.tracking_data t  (cost=0.00..10.00 rows=1000 width=0)
                                                                    ->  XN S3 Query Scan t  (cost=0.00..200000000.00 rows=10000000000 width=1548)
                                                                          ->  S3 Seq Scan ext_wkda_retail_autohero_ad_view_tracking.tracking_data t location:"s3://retail-autohero-ad-view-tracking-prod/tracking_data/" format:PARQUET  (cost=0.00..100000000.00 rows=10000000000 width=1548)
                                                              ->  XN Hash  (cost=18652417602.82..18652417602.82 rows=35870 width=600)
                                                                    ->  XN Hash Join DS_BCAST_INNER  (cost=3514.91..18652417602.82 rows=35870 width=600)
                                                                          Hash Cond: (("outer".id)::text = ("inner".ad_id)::text)
                                                                          ->  XN Seq Scan on ad cad  (cost=0.00..6101.87 rows=610187 width=556)
                                                                          ->  XN Hash  (cost=3425.23..3425.23 rows=35870 width=44)
                                                                                ->  XN Seq Scan on retail_ad rad  (cost=0.00..3425.23 rows=35870 width=44)
                                                                                      Filter: (((retail_country)::text = 'FR'::text) AND ((is_test)::text = 'false'::text))
                                                        ->  XN Hash  (cost=41875000307.30..41875000307.30 rows=29392 width=1032)
                                                              ->  XN Partition Loop  (cost=0.00..41875000307.30 rows=29392 width=1032)
                                                                    ->  XN Seq Scan PartitionInfo of ext_wkda_retail_autohero_cid_tracking.tracking_data  (cost=0.00..12.50 rows=334 width=0)
                                                                          Filter: ((tracking_date)::text >= '2023-08-15'::text)
                                                                    ->  XN S3 Query Scan tracking_data  (cost=0.00..125000000.88 rows=88 width=1032)
                                                                          ->  S3 Seq Scan ext_wkda_retail_autohero_cid_tracking.tracking_data location:"s3://retail-autohero-cid-tracking-prod/tracking_data/" format:PARQUET  (cost=0.00..125000000.00 rows=88 width=1032)
                                                                                Filter: ((raw_cid)::text ~~ '%eWYmFsOKRqK1G9xxj0tyaw%'::text)
                          ->  XN Hash  (cost=11663617511608.35..11663617511608.35 rows=17600 width=564)
                                ->  XN Subquery Scan p  (cost=11663617511256.35..11663617511608.35 rows=17600 width=564)
                                      ->  XN HashAggregate  (cost=11663617511256.35..11663617511432.35 rows=17600 width=2064)
                                            ->  XN Hash Join DS_BCAST_INNER  (cost=41875003895.69..9368467257422.72 rows=229515025383363 width=2064)
                                                  Hash Cond: (("outer".track_id)::text = ("inner".session_id)::text)
                                                  ->  XN Hash Join DS_BCAST_INNER  (cost=3514.91..358035120222.20 rows=1561751669729 width=1548)
                                                        Hash Cond: (("outer".ad_id)::text = ("inner".ad_id)::text)
                                                        ->  XN Partition Loop  (cost=0.00..200200000010.00 rows=10000000000000 width=1548)
                                                              ->  XN Seq Scan PartitionInfo of ext_wkda_retail_statistic_ad_view.retail_statistic_ad_view_data cp  (cost=0.00..10.00 rows=1000 width=0)
                                                              ->  XN S3 Query Scan cp  (cost=0.00..200000000.00 rows=10000000000 width=1548)
                                                                    ->  S3 Seq Scan ext_wkda_retail_statistic_ad_view.retail_statistic_ad_view_data cp location:"s3://retail-statistic-ad-view-prod/retail_statistic_ad_view_data/" format:PARQUET  (cost=0.00..100000000.00 rows=10000000000 width=1548)
                                                        ->  XN Hash  (cost=3425.23..3425.23 rows=35870 width=40)
                                                              ->  XN Seq Scan on retail_ad rad  (cost=0.00..3425.23 rows=35870 width=40)
                                                                    Filter: (((retail_country)::text = 'FR'::text) AND ((is_test)::text = 'false'::text))
                                                  ->  XN Hash  (cost=41875000307.30..41875000307.30 rows=29392 width=1032)
                                                        ->  XN Partition Loop  (cost=0.00..41875000307.30 rows=29392 width=1032)
                                                              ->  XN Seq Scan PartitionInfo of ext_wkda_retail_autohero_cid_tracking.tracking_data  (cost=0.00..12.50 rows=334 width=0)
                                                                    Filter: ((tracking_date)::text >= '2023-08-15'::text)
                                                              ->  XN S3 Query Scan tracking_data  (cost=0.00..125000000.88 rows=88 width=1032)
                                                                    ->  S3 Seq Scan ext_wkda_retail_autohero_cid_tracking.tracking_data location:"s3://retail-autohero-cid-tracking-prod/tracking_data/" format:PARQUET  (cost=0.00..125000000.00 rows=88 width=1032)
                                                                          Filter: ((raw_cid)::text ~~ '%eWYmFsOKRqK1G9xxj0tyaw%'::text)

**Comment by crst** [comment]
Hi @ankush-bindra, thanks for posting the plan.

Indeed external tables were not supported yet. I've added support for the missing operators from the plan, they should not cause parser errors anymore now.

If you find more operators that are not supported yet, please try to post the plan in a code block like this:
```
XN Merge  (cost=35550190915222.17..35550190915222.67 rows=200 width=59)
  Merge Key: a.exp_variant
  ->  XN Network  (cost=35550190915222.17..35550190915222.67 rows=200 width=59)
```
This will keep the original formatting, which makes it easier to add support for the missing operators.

**Comment by ankush-bindra** [comment]
Thanks @crst, it is working fine. Sure, I will keep your suggestion in mind and share the plan in its original format.
